### PR TITLE
Fix memory adapter context priority

### PR DESCRIPTION
**Pull request by maxp-hover**
Paired with Gigi 

We need both of the following situations to work:

1. Flag is globally enabled, we do a context-specific query, it should return true
2. Flag is globally enabled, but we turn it off for a single context. When queried with that context, it should return false.

Currently the first passes but the second failed. This is because the global setting was always taking priority over the context. This PR fixes it.

Will need to push to RubyGems, and update in Hyperion.

### CODE REVIEW

**Comment by matthewjf** [comment]
This PR seems like it's changing behavior and so not technically a refactor. Might seem pedantic, but being clear about that distinction tells us something about how risky a change is.

Do you know how split / flipper handle this case?

**Comment by matthewjf** [comment]
Ok I remember now. The split adapter mimics "global" (context-less) flags, since that concept doesn't exist in Split. Which means that the behavior changes here would be consistent with Split. Makes sense now. 

Probably should be a minor version bump.

**Comment by maxp-hover** [comment]
Yeah all good calls @matthewjf I removed the "refactor" label, and you're correct that it reflects Split now ... it was previously written with Flipper logic in mind. I will change it from patch to minor bump. What do you do to deploy again, `gem build this_feature` and then `gem push this_feature-xxx.gemspec`?

**Comment by matthewjf** [comment]
@maxp-hover Yeah, I used https://github.com/svenfuchs/gem-release#gem-release, but I could never get the `--recurse` option to work. I think I needed to release each gem individually. You could put it into a release script.

**Pull request merged**
